services:
  app:
    image: ghcr.io/arthurlovelin/arthurs-blog:latest
    container_name: arthurs-blog
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - /home/app.local
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - nextjs_cache:/app/.next/cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  nextjs_cache:
