import type { Post } from './blog'

export const mockPosts: Post[] = [
  {
    id: '1',
    slug: 'nextjs-app-router-deep-dive',
    title: 'Next.js App Router 深度解析：从页面到布局的完整指南',
    summary: '深入探讨 Next.js 13+ App Router 的核心概念，包括服务端组件、客户端组件、数据获取模式，以及如何在实际项目中高效地组织代码结构。',
    tags: ['Next.js', 'React', '前端'],
    r2_key: 'posts/nextjs-app-router.md',
    published: true,
    published_at: '2024-03-15T08:00:00Z',
    updated_at: '2024-03-15T08:00:00Z',
  },
  {
    id: '2',
    slug: 'tailwindcss-design-system',
    title: '用 Tailwind CSS 构建设计系统：AppleUI 风格实践',
    summary: '从零开始构建一套基于 Tailwind CSS 的设计系统，涵盖色彩体系、排版规范、间距系统和组件库，并以 Apple 风格为设计目标。',
    tags: ['CSS', 'Tailwind', '设计'],
    r2_key: 'posts/tailwindcss-design-system.md',
    published: true,
    published_at: '2024-03-10T08:00:00Z',
    updated_at: '2024-03-10T08:00:00Z',
  },
  {
    id: '3',
    slug: 'supabase-realtime-features',
    title: 'Supabase Realtime 实战：构建实时协作应用',
    summary: '利用 Supabase 的实时订阅功能，打造支持多人实时协作的应用程序。包括数据库变更监听、实时状态同步和冲突处理策略。',
    tags: ['Supabase', '后端', '实时'],
    r2_key: 'posts/supabase-realtime.md',
    published: true,
    published_at: '2024-02-28T08:00:00Z',
    updated_at: '2024-02-28T08:00:00Z',
  },
  {
    id: '4',
    slug: 'spring-wardrobe-2024',
    title: '2024 春季穿搭灵感：简约与层次感的平衡',
    summary: '春季换装指南，探索如何在日常穿搭中融入当季流行色彩与经典款式，打造既舒适又有品味的日常造型。',
    tags: ['穿搭', '时尚', '生活'],
    r2_key: 'posts/spring-wardrobe-2024.md',
    published: true,
    published_at: '2024-02-20T08:00:00Z',
    updated_at: '2024-02-20T08:00:00Z',
  },
  {
    id: '5',
    slug: 'typescript-generics-advanced',
    title: 'TypeScript 高级泛型：让类型系统真正为你服务',
    summary: '深入理解 TypeScript 泛型的高级用法，包括条件类型、映射类型、模板字面量类型，以及如何用这些工具解决复杂的类型推导问题。',
    tags: ['TypeScript', '编程', '前端'],
    r2_key: 'posts/typescript-generics.md',
    published: true,
    published_at: '2024-02-10T08:00:00Z',
    updated_at: '2024-02-10T08:00:00Z',
  },
  {
    id: '6',
    slug: 'cloudflare-r2-setup',
    title: 'Cloudflare R2 对象存储：从配置到生产环境',
    summary: '完整的 Cloudflare R2 使用指南，包括 Bucket 创建、访问权限配置、与 Next.js 集成，以及在国内网络环境下的最佳实践。',
    tags: ['云服务', 'Cloudflare', '后端'],
    r2_key: 'posts/cloudflare-r2.md',
    published: true,
    published_at: '2024-01-25T08:00:00Z',
    updated_at: '2024-01-25T08:00:00Z',
  },
]

export const mockCategories: { name: string; count: number; slug: string }[] = [
  { name: '前端开发', count: 8, slug: 'frontend' },
  { name: '后端技术', count: 5, slug: 'backend' },
  { name: '穿搭生活', count: 6, slug: 'lifestyle' },
  { name: '设计思考', count: 4, slug: 'design' },
  { name: '工具效率', count: 3, slug: 'tools' },
]

export const mockTags: { tag: string; count: number }[] = [
  { tag: 'Next.js', count: 5 },
  { tag: 'React', count: 6 },
  { tag: 'TypeScript', count: 4 },
  { tag: 'Tailwind', count: 3 },
  { tag: '穿搭', count: 6 },
  { tag: 'Supabase', count: 2 },
  { tag: '前端', count: 7 },
  { tag: '设计', count: 4 },
  { tag: '生活', count: 5 },
  { tag: '云服务', count: 2 },
  { tag: '后端', count: 3 },
  { tag: 'CSS', count: 3 },
]
